### PR TITLE
Re-organize new_design branch and merge back into master

### PR DESCRIPTION
**Pull request by g2flyer**

### CODE REVIEW

**Comment by mbrandenburger** [comment]
Seems that PUMLs don't have licences headers thus travis complains.
Adding the following seems to work fine with the plantuml compiler
```
SPDX-License-Identifier: Apache-2.0

@startuml
```

**Comment by g2flyer** [comment]
> Seems that PUMLs don't have licences headers thus travis complains.
> Adding the following seems to work fine with the plantuml compiler
> 
> ```
> SPDX-License-Identifier: Apache-2.0
> 
> @startuml
> ```

Good catch. i didn't touch any file content so was only testing make build/clean. Seems we ignored the license check on earlier commits.

In any case, i've added now headers, also adding copyright notice.  Note, though, comment lines start with ' or (blocks as /' ... '/, see https://plantuml.com/commons

**Comment by bvavala** [comment]
missing the readme file

**Comment by g2flyer** [comment]
> missing the readme file

what readme?

**Comment by bvavala** [comment]
I thought we had agreed to put a readme file and clarify what is implemented, what is not, and references to the code. This is not clear now.

**Comment by g2flyer** [comment]
> I thought we had agreed to put a readme file and clarify what is implemented, what is not, and references to the code. This is not clear now.

We didn't discuss anything like that on Tuesday (and nothing corresponding shows up in the minutes)?  Right now what is in design/concept-release should be what is implemented in the concept-release tag and nothing in design/fabricv2... is implemented yet (except, of course, umls which just describe fabric v2 lifecycle or alike).    In any case, this PR is merged now.  Given that  you will have to touch the puml and hence docs/design for your AR to incorporate the changes/clarifications discussed in the Phoenix F2F, why don't you make a first stab of such a readme in your puml-update PR?

**Comment by bvavala** [comment]
> We didn't discuss anything like that on Tuesday (and nothing corresponding shows up in the minutes)? 

Making sure that we do not cause confusion has always been the reason why this branch was not merged before.

> Right now what is in design/concept-release should be what is implemented in the concept-release tag and nothing in design/fabricv2... is implemented yet (except, of course, umls which just describe fabric v2 lifecycle or alike). 

This is exactly the readme file I am talking about.

> In any case, this PR is merged now.

If you see the log, my comment and the merge were concurrent -- though I was the assignee anyway.

> Given that you will have to touch the puml and hence docs/design for your AR to incorporate the changes/clarifications discussed in the Phoenix F2F, why don't you make a first stab of such a readme in your puml-update PR?

Sure I can.

**Pull request merged**
