### PR TITLE
Typos: some corrections

### PR DESCRIPTION
**Pull request by axelsimon**

### CODE REVIEW

**Comment by mbrandenburger** [comment]
Thanks for this fix! Could you please squash your commits and fix the sign-off. Happy to merge it!

**Comment by axelsimon** [comment]
Hi! I'd separated them for ease of understanding and did the editing from the Github web interface, which doesn't offer squashing.
Tried to squash and sign-off locally. Let me know if this ok.

**Comment by mbrandenburger** [comment]
> Hi! I'd separated them for ease of understanding and did the editing from the Github web interface, which doesn't offer squashing.
> Tried to squash and sign-off locally. Let me know if this ok.

mh ... seems that your patch causes a conflict now :/ ... and for successful DCO check we need a sign-off for every commit.

I suggest that you locally do a `rebase -i`, squash everything into as many commits as needed (for logical separation) and make sure that every commit has the sign-off. Then you do a `push -f`.

**Comment by g2flyer** [comment]
Hi @axelsimon, did you have time to look at Marcus' comment on your PR?  We would need the DCO to accept the PR and it currently also doesn't merge with master. thanks!

**Comment by mbrandenburger** [comment]
I will close this PR due to low activity. I am happy to reopen.

**Comment by axelsimon** [comment]
Hey @mbrandenburger, i finally managed to rebase all the changes properly and squash all commits to a single logical commit, which is signed-off. I think these improvements should now be mergeable.
Would you please reopen the PR? :)

**Comment by swetharepakula** [comment]
Github doesn't let us reopen a PR if the underlying branch was updated after the PR was closed. Can you create a new PR with the updated branch?

**Pull request closed without merging**
