### PR TITLE
Make peer.sh also work for non-fpc code

### PR DESCRIPTION
**Pull request by g2flyer**
**What this PR does / why we need it**:

This PR improves #320 to allow peer.sh also be used for non-fpc chaincode (and hence allow upgrading the deployment integration test) 

**Which issue(s) this PR fixes**:

No explicit issue but addresses limitation mentioned in #320 

**Special notes for your reviewer**:

See #320 for hints on how to test. For non-fpc chaincode i used `marbles02`, i.e., extended steps from #320 with
 ```
      # marbles02
      LBL=marbles02
      VER=0
      CC_LANG=golang
      CC_PATH=github.com/hyperledger/fabric-samples/chaincode/marbles02/go
```

**Does this PR introduce a user-facing changes and/or breaks backward compatability?**:

it should not break backwards compatability; it does add though now also --help documentation on the --sgx-mode/-s flags for package introduced in #320

### CODE REVIEW

**Comment by Jordy24** [comment]
`panic: Could not find plugin at path ../../plugins/ercc-decorator.so: stat ../../plugins/ercc-decorator.so: no such file or directory` this is the error am getting... or maybe am not testing correct ?

**Comment by mbrandenburger** [comment]
> `panic: Could not find plugin at path ../../plugins/ercc-decorator.so: stat ../../plugins/ercc-decorator.so: no such file or directory` this is the error am getting... or maybe am not testing correct ?

doube check that there is the ercc decorator `ercc-decorator.so` in `$FPC_PATH/plugins/` when you run the test.

make sure you run the test after a fresh `make clean && make`.

**Comment by Jordy24** [comment]
could you show the command you are using for testing?? am using the script from #320 and thats not working for me

**Comment by g2flyer** [comment]
> I am using the script from #320 and thats not working for me

Can you be a bit more specific on what you did and what did not work?  Note the code fragment i added to #320 are not a script to run automatically but just a toolbox of commands to easily test manually.   E.g., i would do ledger_init, then pick one of the example chaincode and set there variables and then one by one do the installation and try the invoke corresponding to that example chaincode (as indicated by the comment above the invoke). then i might try another chaincode do installation and test invoke, and finally do the shutdown. All of that essentially should work.   But of course it also depends that you started from a clean build first (e.g., by doing what marcus has said or an even "cleaner" `make clobber all`

**Pull request merged**
