### PR TITLE
Update hello world example

### PR DESCRIPTION
**Pull request by mbrandenburger**
**What this PR does / why we need it**:
Integrate the `lifecycle chaincode createenclave` command into the
hello world example.

Signed-off-by: bur <bur@zurich.ibm.com>

**Which issue(s) this PR fixes**:

Links to #358

**Special notes for your reviewer**:

**Does this PR introduce a user-facing changes and/or breaks backward compatability?**:

```

### CODE REVIEW

**Comment by mbrandenburger** [comment]
@g2flyer Oh, I've just noticed that you are addressing in your current WIP PR #388.

**Comment by g2flyer** [comment]
> @g2flyer Oh, I've just noticed that you are addressing in your current WIP PR #388.

Do you still want it as a separate PR or is my version ok?  If so, i would propose to close this one and rely on #388?

**Comment by mbrandenburger** [comment]
I would consider this PR to be merged as I also reworked the text around `### Install and instantiate chaincode on the peer`

**Comment by mbrandenburger** [comment]
Also, removing these changes from your PR will make it also smaller, which is always good! :)

**Comment by bvavala** [comment]
assigning this  to @g2flyer  as I am fine merging the updates here or elsewhere.

**Pull request merged**
