### PR TITLE
Use local license script

### PR DESCRIPTION
**Pull request by swetharepakula**
- makes exclusions/exceptions easier to control

### CODE REVIEW

**Comment by g2flyer** [comment]
I guess i'm to blame that we referenced fabric script to prevent duplication but i guess with things like json or so it is too painful/too frequent that it fails.    Note though when i looked at it in the past the fabric script was not robust and would have failed on it's own file if run on the complete repo, not only file from last diff, and that time it looked as some of the issues would not be easy to fix in a robust way.  But we can say on how it goes, it certainly should be better than now :-)   One thing, though: might be worth to explicitly attribute where we copied it from and from which version/commit (and/or mark also our own additions)?   Just in case there is at some point a fabric improvement which we would like to to re-use ....

**Comment by swetharepakula** [comment]
I like that idea, I will put a comment in the script

**Comment by g2flyer** [comment]
btw: i've tried to run the check on all files rather than only from the ones in the last commit and a few other patterns should be excluded
```
\.patch$
\.clang_format$
\.gitignore$
test_blocks/mychannel-blocks
common/base64
common/parson
```
Also flagged were various .puml files in doc and *config.js files in the demo front-end. However, they should be able to support comments with licenses, so we should rather fix them eventually than filter them out ...

BTW: filter on all files i just used `CHECK=$(find . -path ./.git -prune -o -type f -print | tr '\n' ' ')` instead of the existing `CHECK` definitions ..

**Comment by mbrandenburger** [comment]
> btw: i've tried to run the check on all files rather than only from the ones in the last commit and a few other patterns should be excluded
> 
> ```
> \.patch$
> \.clang_format$
> \.gitignore$
> test_blocks/mychannel-blocks
> common/base64
> common/parson
> ```

sounds reasonable.

> Also flagged were various .puml files in doc and *config.js files in the demo front-end. However, they should be able to support comments with licenses, so we should rather fix them eventually than filter them out ...
> 

I suggest we create another PR for fixing those files missing the license.

**Comment by swetharepakula** [comment]
I have added the extra patterns. `.gitignore` can support comments so did not add that one.
We can start using the shorter license `SPDX-License-Identifier: Apache-2.0`

For the followup PR to fix the license headers, the following are the files that need to be fixed:
```
./.gitignore
./CODEOWNERS
./common/.gitignore
./common/json/parson.c
./common/json/parson.h
./config/ias/.gitignore
./demo/.gitignore
./demo/client/frontend/.dockerignore
./demo/client/frontend/.env.development
./demo/client/frontend/.gitignore
./demo/client/frontend/babel.config.js
./demo/client/frontend/vue.config.js
./docs/.gitignore
./docs/fpc-api.puml
./docs/fpc-lifecycle.puml
./ecc/.gitignore
./ecc_enclave/.gitignore
./ecc_enclave/enclave/enclave.lds
./tlcc/.gitignore
./tlcc_enclave/.gitignore
./tlcc_enclave/enclave/enclave.lds
./tlcc_enclave/protos/fabric.options
./tlcc_enclave/protos/google/protobuf/empty.proto
./tlcc_enclave/protos/google/protobuf/timestamp.proto
./utils/fabric/.gitignore
./utils/fabric/get-fabric-container-name.go
```

**Comment by g2flyer** [comment]
> I have added the extra patterns. `.gitignore` can support comments so did not add that one.
Good point

> We can start using the shorter license `SPDX-License-Identifier: Apache-2.0`
That should have been the plan already but i guess all best layed out plans fail from time to time ...:-)
> For the followup PR to fix the license headers, the following are the files that need to be fixed:
> 
> ```
> ./.gitignore
> ./CODEOWNERS
> ./common/.gitignore
> ./common/json/parson.c
> ./common/json/parson.h

I don't think we are allowed to add our own license check to the parson files as we copy/pasted them. Hence why i put them earlier in the exclusion list ..

> ./config/ias/.gitignore
> ./demo/.gitignore
> ./demo/client/frontend/.dockerignore
> ./demo/client/frontend/.env.development
> ./demo/client/frontend/.gitignore
> ./demo/client/frontend/babel.config.js
> ./demo/client/frontend/vue.config.js
> ./docs/.gitignore
> ./docs/fpc-api.puml
> ./docs/fpc-lifecycle.puml
> ./ecc/.gitignore
> ./ecc_enclave/.gitignore
> ./ecc_enclave/enclave/enclave.lds
> ./tlcc/.gitignore
> ./tlcc_enclave/.gitignore
> ./tlcc_enclave/enclave/enclave.lds
> ./tlcc_enclave/protos/fabric.options
> ./tlcc_enclave/protos/google/protobuf/empty.proto
> ./tlcc_enclave/protos/google/protobuf/timestamp.proto

also not sure about these: these are copy/paste google files which already have an implied license?

> ./utils/fabric/.gitignore
> ./utils/fabric/get-fabric-container-name.go
> ```

**Comment by swetharepakula** [comment]
> > I have added the extra patterns. `.gitignore` can support comments so did not add that one.
> > Good point
> 
> > We can start using the shorter license `SPDX-License-Identifier: Apache-2.0`
> > That should have been the plan already but i guess all best layed out plans fail from time to time ...:-)
> > For the followup PR to fix the license headers, the following are the files that need to be fixed:
> > ```
> > ./.gitignore
> > ./CODEOWNERS
> > ./common/.gitignore
> > ./common/json/parson.c
> > ./common/json/parson.h
> > ```
Oh okay, I misunderstood the parson regex. I saw `.c` and `.h`. Will fix in followup
> also not sure about these: these are copy/paste google files which already have an implied license?
> 
> > ./utils/fabric/.gitignore
> > ./utils/fabric/get-fabric-container-name.go

The last one actually was just flagged for not having the shorter license, not sure about the .gitignore though, was that copied over too?

**Comment by swetharepakula** [comment]
updated list of files to be fixed:
```
./.gitignore
./CODEOWNERS
./common/.gitignore
./config/ias/.gitignore
./demo/.gitignore
./demo/client/frontend/.dockerignore
./demo/client/frontend/.env.development
./demo/client/frontend/.gitignore
./demo/client/frontend/babel.config.js
./demo/client/frontend/vue.config.js
./docs/.gitignore
./docs/fpc-api.puml
./docs/fpc-lifecycle.puml
./ecc/.gitignore
./ecc_enclave/.gitignore
./ecc_enclave/enclave/enclave.lds
./tlcc/.gitignore
./tlcc_enclave/.gitignore
./tlcc_enclave/enclave/enclave.lds
./tlcc_enclave/protos/fabric.options
./tlcc_enclave/protos/google/protobuf/empty.proto
./tlcc_enclave/protos/google/protobuf/timestamp.proto
./utils/fabric/.gitignore
```

**Comment by g2flyer** [comment]
> > also not sure about these: these are copy/paste google files which already have an implied license?
> > > ./utils/fabric/.gitignore
> > > ./utils/fabric/get-fabric-container-name.go
> 
> The last one actually was just flagged for not having the shorter license, not sure about the .gitignore though, was that copied over too?

Sorry, my comment was misleading: i was referring to the two google *.proto files  (not the .gitignore and get-fabric-ontainer-name.go) when i said that these also shouldn't be modified

**Comment by swetharepakula** [comment]
Ahhh, in that case we can ignore the google directory itself since it is all copied

**Comment by swetharepakula** [comment]
Should be fixed now.

New list:
```
./.gitignore
./CODEOWNERS
./common/.gitignore
./config/ias/.gitignore
./demo/.gitignore
./demo/client/frontend/.dockerignore
./demo/client/frontend/.env.development
./demo/client/frontend/.gitignore
./demo/client/frontend/babel.config.js
./demo/client/frontend/vue.config.js
./docs/.gitignore
./docs/fpc-api.puml
./docs/fpc-lifecycle.puml
./ecc/.gitignore
./ecc_enclave/.gitignore
./ecc_enclave/enclave/enclave.lds
./tlcc/.gitignore
./tlcc_enclave/.gitignore
./tlcc_enclave/enclave/enclave.lds
./tlcc_enclave/protos/fabric.options
./utils/docker-compose/bin/configtxgen
./utils/docker-compose/bin/configtxlator
./utils/docker-compose/bin/cryptogen
./utils/docker-compose/bin/discover
./utils/docker-compose/bin/fabric-ca-client
./utils/docker-compose/bin/idemixgen
./utils/docker-compose/bin/orderer
./utils/docker-compose/bin/peer
./utils/fabric/.gitignore
```

**Pull request merged**
