### PR TITLE
Godoc for SDK functions

### PR DESCRIPTION
**Pull request by g2flyer**
**What this PR does / why we need it**:

This adds godoc comments for the Client and Management SDK API functions we reference in the RFC.
Also includes some minor refactoring of api to make more uniform, minimize exports, closer to what Fabric does (e.g., no Interface suffix for interfaces) and get rid of some go-lint warnings.
Also added two missing .gitignores and a convenience .gitignore for the case you have a local copy of the helloworld example

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing changes and/or breaks backward compatability?**:

```

### CODE REVIEW

**Review by mbrandenburger — APPROVED** [review]
LGTM! Thanks Michael

**Comment by mbrandenburger** [comment]
Travis check complains about missing license headers in `.gitignore`, we can ignore this.

**Comment by mbrandenburger** [comment]
@bvavala any objections to merge? :)

**Comment by g2flyer** [comment]
> Travis check complains about missing license headers in `.gitignore`, we can ignore this.

Strangely, it didn't complain when i tested in my VM.  But added it now also as exception to the licence check script

**Review by bvavala — APPROVED** [review]
need to add some more exceptions for .gitignore

**Comment by g2flyer** [comment]
> need to add some more exceptions for .gitignore

I too naively copy/pasted from the `.gitmodules` rule which i've added during the re-integration to solve another licence-header issue. Removed now the preceeding '^' made the rule match only on the top-level. Hopefully now it goes through ....

**Pull request merged**
