### PR TITLE
Make fabric-samples work again and easier to use

### PR DESCRIPTION
**Pull request by g2flyer**
test-networks test do not work in master. This is PR fixes some obvious issues, updates docu and also adds a patch to the test-network network.sh which makes it easy to look at peer logs and alike.   It should also display now logs from cgo.

PS: it's strange, in a simple test program, the `puts` used in cgo does display info on stdout, but not for `ercc` where puts output is simply swallowed and you have to explicitly set the output callback to something else.  
BTW: given that we used flogging so far, why are we using now "log"? Would be nice to be somewhat consistent ....

### CODE REVIEW

**Comment by g2flyer** [comment]
BTW: below an extract of the error.
```
....
ecc.peer0.org1.example.com     | 2020-12-01 00:08:18.612 UTC [enclave] Init -> INFO 003 Create credentials
: serialized_attested_data:{[fpc.AttestedData]:{cc_params:{chaincode_id:"ecc"  version:"1.0"  sequence:1
channel_id:"mychannel"}  host_params:{peer_msp_id:"Org1MSP"  peer_endpoint:"peer0.peer1.example.com:7051"}
  enclave_vk:"0Y0\x13\x06\x07*\x86H\xce=\x02\x01\x06\x08*\x86H\xce=\x03\x01\x07\x03B\x00\x04g\xc7\xf6\xd7J
\xdf\xe6\x9f}\x15&(\xac\xa1g\x00\xb0L\xd6I?[\xee\xc2{▒▒\x2c\xc1t\xe8g\x8cPR\xb9\xe9U'C\xf8\xf3\x8e\xd4\xeaxb6D\xc2\xc6w\xbb\xf9\xa5'\xb6\x1f\xe9\x04r\xe1\xe8\xbf\x0c"}}  attestation:"{\"attestation_type\":\"simul
ated\",\"attestation\":\"MA==\"}"
ercc.peer0.org1.example.com    | 2020/12/01 00:08:18 Invoke [registerEnclave]
ercc.peer0.org1.example.com    | 2020/12/01 00:08:18 RegisterEnclave
ercc.peer0.org1.example.com    | 2020/12/01 00:08:18 - verifying attested data ({{{} [] [] 0xc000113270} 0
 [] chaincode_id:"ecc" version:"1.0" sequence:1 channel_id:"mychannel" peer_msp_id:"Org1MSP" peer_endpoint
:"peer0.peer1.example.com:7051" [48 89 48 19 6 7 42 134 72 206 61 2 1 6 8 42 134 72 206 61 3 1 7 3 66 0 4
103 199 246 215 74 223 230 159 125 21 38 40 172 161 103 0 176 76 214 73 63 91 238 194 123 201 137 28 193 1
16 232 103 140 80 82 185 233 85 39 67 248 243 127 142 212 234 182 68 194 198 119 187 249 165 39 182 31 233
 4 114 225 232 191 12] [] }) against evidence ({"attestation_type":"simulated","evidence":"MA=="})
ercc.peer0.org1.example.com    | free(): double free detected in tcache 2
ercc.peer0.org2.example.com    | 2020/12/01 00:08:18 Invoke [registerEnclave]
ercc.peer0.org2.example.com    | 2020/12/01 00:08:18 RegisterEnclave
ercc.peer0.org2.example.com    | 2020/12/01 00:08:18 - verifying attested data ({{{} [] [] 0xc00018b270} 0
 [] chaincode_id:"ecc" version:"1.0" sequence:1 channel_id:"mychannel" peer_msp_id:"Org1MSP" peer_endpoint
:"peer0.peer1.example.com:7051" [48 89 48 19 6 7 42 134 72 206 61 2 1 6 8 42 134 72 206 61 3 1 7 3 66 0 4
103 199 246 215 74 223 230 159 125 21 38 40 172 161 103 0 176 76 214 73 63 91 238 194 123 201 137 28 193 1
16 232 103 140 80 82 185 233 85 39 67 248 243 127 142 212 234 182 68 194 198 119 187 249 165 39 182 31 233
 4 114 225 232 191 12] [] }) against evidence ({"attestation_type":"simulated","evidence":"MA=="})
ercc.peer0.org1.example.com    | SIGABRT: abort
ercc.peer0.org1.example.com    | PC=0x7ff1549c9fb7 m=5 sigcode=18446744073709551610
ercc.peer0.org1.example.com    |
ercc.peer0.org1.example.com    | goroutine 0 [idle]:
ercc.peer0.org1.example.com    | runtime: unknown pc 0x7ff1549c9fb7
ercc.peer0.org1.example.com    | stack: frame={sp:0x7ff12c8d4a40, fp:0x0} stack=[0x7ff12c0d5288,0x7ff12c8d
4e88)
ercc.peer0.org1.example.com    | 00007ff12c8d4940:  00007ff110001dc0  00007ff155a17073
ercc.peer0.org1.example.com    | 00007ff12c8d4950:  0000000000000005  0000000000000000
...
...

**Comment by bvavala** [comment]
> BTW: below an extract of the error.
> 
> ```
> ....
> ecc.peer0.org1.example.com     | 2020-12-01 00:08:18.612 UTC [enclave] Init -> INFO 003 Create credentials
> : serialized_attested_data:{[fpc.AttestedData]:{cc_params:{chaincode_id:"ecc"  version:"1.0"  sequence:1
> channel_id:"mychannel"}  host_params:{peer_msp_id:"Org1MSP"  peer_endpoint:"peer0.peer1.example.com:7051"}
>   enclave_vk:"0Y0\x13\x06\x07*\x86H\xce=\x02\x01\x06\x08*\x86H\xce=\x03\x01\x07\x03B\x00\x04g\xc7\xf6\xd7J
> \xdf\xe6\x9f}\x15&(\xac\xa1g\x00\xb0L\xd6I?[\xee\xc2{▒▒\x2c\xc1t\xe8g\x8cPR\xb9\xe9U'C\xf8\xf3\x8e\xd4\xeaxb6D\xc2\xc6w\xbb\xf9\xa5'\xb6\x1f\xe9\x04r\xe1\xe8\xbf\x0c"}}  attestation:"{\"attestation_type\":\"simul
> ated\",\"attestation\":\"MA==\"}"
> ercc.peer0.org1.example.com    | 2020/12/01 00:08:18 Invoke [registerEnclave]
> ercc.peer0.org1.example.com    | 2020/12/01 00:08:18 RegisterEnclave
> ercc.peer0.org1.example.com    | 2020/12/01 00:08:18 - verifying attested data ({{{} [] [] 0xc000113270} 0
>  [] chaincode_id:"ecc" version:"1.0" sequence:1 channel_id:"mychannel" peer_msp_id:"Org1MSP" peer_endpoint
> :"peer0.peer1.example.com:7051" [48 89 48 19 6 7 42 134 72 206 61 2 1 6 8 42 134 72 206 61 3 1 7 3 66 0 4
> 103 199 246 215 74 223 230 159 125 21 38 40 172 161 103 0 176 76 214 73 63 91 238 194 123 201 137 28 193 1
> 16 232 103 140 80 82 185 233 85 39 67 248 243 127 142 212 234 182 68 194 198 119 187 249 165 39 182 31 233
>  4 114 225 232 191 12] [] }) against evidence ({"attestation_type":"simulated","evidence":"MA=="})
> ercc.peer0.org1.example.com    | free(): double free detected in tcache 2
> ercc.peer0.org2.example.com    | 2020/12/01 00:08:18 Invoke [registerEnclave]
> ercc.peer0.org2.example.com    | 2020/12/01 00:08:18 RegisterEnclave
> ercc.peer0.org2.example.com    | 2020/12/01 00:08:18 - verifying attested data ({{{} [] [] 0xc00018b270} 0
>  [] chaincode_id:"ecc" version:"1.0" sequence:1 channel_id:"mychannel" peer_msp_id:"Org1MSP" peer_endpoint
> :"peer0.peer1.example.com:7051" [48 89 48 19 6 7 42 134 72 206 61 2 1 6 8 42 134 72 206 61 3 1 7 3 66 0 4
> 103 199 246 215 74 223 230 159 125 21 38 40 172 161 103 0 176 76 214 73 63 91 238 194 123 201 137 28 193 1
> 16 232 103 140 80 82 185 233 85 39 67 248 243 127 142 212 234 182 68 194 198 119 187 249 165 39 182 31 233
>  4 114 225 232 191 12] [] }) against evidence ({"attestation_type":"simulated","evidence":"MA=="})
> ercc.peer0.org1.example.com    | SIGABRT: abort
> ercc.peer0.org1.example.com    | PC=0x7ff1549c9fb7 m=5 sigcode=18446744073709551610
> ercc.peer0.org1.example.com    |
> ercc.peer0.org1.example.com    | goroutine 0 [idle]:
> ercc.peer0.org1.example.com    | runtime: unknown pc 0x7ff1549c9fb7
> ercc.peer0.org1.example.com    | stack: frame={sp:0x7ff12c8d4a40, fp:0x0} stack=[0x7ff12c0d5288,0x7ff12c8d
> 4e88)
> ercc.peer0.org1.example.com    | 00007ff12c8d4940:  00007ff110001dc0  00007ff155a17073
> ercc.peer0.org1.example.com    | 00007ff12c8d4950:  0000000000000005  0000000000000000
> ...
> ...
> ```

I think I have already solved this.
We need integration tests and a repo cleanup.

**Comment by g2flyer** [comment]
> I think I have already solved this.

Cool

> We need integration tests and a repo cleanup.

Well, guess why i was working on this.  It did actually work in an earlier version, that's how i tested the integration of the attestation2evidence integration into the admin sdk.  But somehow the recent PR must have broken a number of things.  Getting tests with ecc_mock working is of course no integration test yet, let alone an automated one.  However, we better get this first working again before we go to the endeavor of splicing the ecc_mock front-end and your back-end together ...

**Comment by g2flyer** [comment]
> > I think I have already solved this.
> 
> Cool

Indeed, the double/wrong defer was the problem.  I got fooled into thinking that the C-function was not called as i didn't see any debug statement i added to `verify_evidence` in `common/crypto/attestation-api/evidence/verify-evidence.cpp`. But turns out, something is wrong with our enclave logging which doesn't show up even though i have defined `SGX_BUILD=DEBUG` in `config.override.mk` ...

**Review by bvavala — APPROVED** [review]
lgtm

**Pull request merged**
